# Generated by Django 5.2 on 2025-07-31 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arvore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuidador', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=200)),
                ('especie', models.CharField(max_length=100)),
                ('data_plantio', models.DateField()),
                ('fotos', models.ImageField(blank=True, null=True, upload_to='fotos_arvores/')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('viva', 'Viva'), ('morta', 'Morta'), ('sem_info', 'Sem Informação')], default='sem_info', max_length=10)),
            ],
        ),
    ]
