# Generated by Django 5.2 on 2025-09-01 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipe_roxo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantacuidador',
            name='status_planta',
            field=models.CharField(choices=[('VIVA', 'Planta Viva'), ('MORTA', 'Planta Morta'), ('REPLANTADA', 'Replantada')], default='VIVA', max_length=20),
        ),
        migrations.CreateModel(
            name='PlantaHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='plantas/historico/')),
                ('data_evento', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('status_planta', models.CharField(choices=[('VIVA', 'Planta Viva'), ('MORTA', 'Planta Morta'), ('REPLANTADA', 'Replantada')], default='VIVA', max_length=20)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='ipe_roxo.plantacuidador')),
            ],
        ),
    ]
