# Generated by Django 5.2 on 2025-08-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipe_roxo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='funcao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
