# Generated by Django 5.2 on 2025-08-01 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipe_roxo', '0002_colaborador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('especie', models.CharField(max_length=100)),
                ('idade_aproximada', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='plantas_fotos/')),
                ('cuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipe_roxo.cuidador')),
            ],
        ),
        migrations.DeleteModel(
            name='Arvore',
        ),
        migrations.DeleteModel(
            name='Colaborador',
        ),
    ]
