# Generated by Django 5.2 on 2025-08-10 01:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipe_roxo', '0002_customuser_funcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantacuidador',
            name='horario_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
