# Generated by Django 5.2 on 2025-08-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipe_roxo', '0003_cuidador_planta_delete_arvore_delete_colaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='data_plantio',
            field=models.DateField(blank=True, null=True, verbose_name='Data do plantio'),
        ),
    ]
