# Generated by Django 5.2 on 2025-08-10 01:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipe_roxo', '0003_plantacuidador_horario_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantacuidador',
            name='horario_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
