# Generated by Django 5.2 on 2025-08-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipe_roxo', '0004_alter_plantacuidador_horario_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantacuidador',
            name='telefone',
            field=models.CharField(max_length=11),
        ),
    ]
