# Generated by Django 5.2 on 2025-08-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipe_roxo', '0004_planta_data_plantio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arvore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuidador', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=200)),
                ('especie', models.CharField(max_length=100)),
                ('data_plantio', models.DateField()),
                ('fotos', models.ImageField(blank=True, null=True, upload_to='fotos_arvores/')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('viva', 'Viva'), ('morta', 'Morta'), ('sem_info', 'Sem Informação')], default='sem_info', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PlantaCuidador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=20)),
                ('especie', models.CharField(max_length=100)),
                ('idade', models.CharField(blank=True, max_length=50, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_plantas/')),
            ],
        ),
        migrations.RemoveField(
            model_name='planta',
            name='cuidador',
        ),
        migrations.DeleteModel(
            name='Cuidador',
        ),
        migrations.DeleteModel(
            name='Planta',
        ),
    ]
