# Generated by Django 5.2 on 2025-08-10 01:52
from django.db import migrations, models
import uuid
from django.utils import timezone

def set_numero_registro(apps, schema_editor):
    """Define NULL para registros existentes (não gera números retroativos)"""
    PlantaCuidador = apps.get_model('ipe_roxo', 'PlantaCuidador')
    PlantaCuidador.objects.all().update(numero_registro=None)

class Migration(migrations.Migration):
    dependencies = [
        ('ipe_roxo', '0005_alter_plantacuidador_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantacuidador',
            name='numero_registro',
            field=models.CharField(
                max_length=12,
                unique=True,
                null=True,  # Permite NULL para registros antigos
                blank=True,
                editable=False
            ),
        ),
    ]