# Generated by Django 5.2 on 2025-08-10 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipe_roxo', '0006_plantacuidador_numero_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantacuidador',
            name='admin_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formularios_revisados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plantacuidador',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente de revisão'), ('APROVADO', 'Aprovado'), ('CORRECAO', 'Necessita correções')], default='pendente', max_length=10),
        ),
    ]
