# Generated by Django 5.2 on 2025-08-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipe_roxo', '0007_plantacuidador_admin_responsavel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantacuidador',
            name='motivo_correcao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
